# Generated by Django 5.2.16 on 2026-08-01 20:38

import apps.fuel.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='code')),
                ('is_system', models.BooleanField(default=False, verbose_name='system')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'fuel type',
                'verbose_name_plural': 'fuel types',
                'db_table': 'fuel_fuel_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Refueling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateField(verbose_name='date')),
                ('station_name', models.CharField(blank=True, help_text='Name of the gas station', max_length=100, verbose_name='station name')),
                ('odometer', models.PositiveIntegerField(help_text='Current odometer reading', verbose_name='odometer (km)')),
                ('liters', models.DecimalField(decimal_places=3, help_text='Amount of fuel in liters', max_digits=8, verbose_name='liters')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount paid', max_digits=10, verbose_name='total amount')),
                ('price_per_liter', models.DecimalField(blank=True, decimal_places=4, help_text='Price per liter (calculated if not provided)', max_digits=8, null=True, verbose_name='price per liter')),
                ('is_full_tank', models.BooleanField(default=True, help_text='Was the tank filled to full?', verbose_name='full tank')),
                ('is_partial', models.BooleanField(default=False, help_text='Was this a partial refueling?', verbose_name='partial')),
                ('missed_previous_fillup', models.BooleanField(default=False, help_text='Did you miss recording the previous full tank?', verbose_name='missed previous fillup')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=apps.fuel.models.fuel_attachment_upload_path, verbose_name='attachment')),
                ('consumption_km_l', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated fuel consumption in km/l', max_digits=8, null=True, verbose_name='consumption (km/l)')),
                ('distance_since_last_full', models.PositiveIntegerField(blank=True, help_text='Distance traveled since last full tank', null=True, verbose_name='distance since last full')),
                ('cost_per_km', models.DecimalField(blank=True, decimal_places=4, help_text='Cost per kilometer', max_digits=8, null=True, verbose_name='cost per km')),
                ('is_outlier', models.BooleanField(default=False, help_text='Is this consumption an outlier?', verbose_name='outlier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refuelings', to='fuel.fueltype', verbose_name='fuel type')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuelings', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'refueling',
                'verbose_name_plural': 'refuelings',
                'db_table': 'fuel_refueling',
                'ordering': ['-occurred_at', '-odometer'],
            },
        ),
        migrations.AddIndex(
            model_name='fueltype',
            index=models.Index(fields=['user', 'is_active'], name='fuel_fuel_t_user_id_929f71_idx'),
        ),
        migrations.AddIndex(
            model_name='refueling',
            index=models.Index(fields=['vehicle', 'occurred_at'], name='fuel_refuel_vehicle_cef93e_idx'),
        ),
        migrations.AddIndex(
            model_name='refueling',
            index=models.Index(fields=['vehicle', 'odometer'], name='fuel_refuel_vehicle_81d4af_idx'),
        ),
        migrations.AddIndex(
            model_name='refueling',
            index=models.Index(fields=['vehicle', 'is_full_tank', 'occurred_at'], name='fuel_refuel_vehicle_de90fc_idx'),
        ),
    ]
