# Generated by Django 5.2.17 on 2026-08-17 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel", "0002_alter_refueling_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="fueltype",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuel_types",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
