# Generated by Django 5.1.7 on 2026-08-17 01:00

from django.db import migrations


def create_system_fuel_types(apps, schema_editor):
    """Create system-wide fuel types."""
    FuelType = apps.get_model("fuel", "FuelType")

    names = [
        ("Gasolina comum", "gasoline"),
        ("Gasolina aditivada", "premium_gasoline"),
        ("Etanol", "ethanol"),
        ("Etanol aditivado", "premium_ethanol"),
        ("Diesel", "diesel"),
        ("GNV", "cng"),
        ("Elétrico", "electric"),
    ]

    for name, code in names:
        FuelType.objects.get_or_create(
            user=None,
            name=name,
            defaults={
                "code": code,
                "is_system": True,
                "is_active": True,
            },
        )


def reverse_fuel_types(apps, schema_editor):
    """Remove system-wide fuel types."""
    FuelType = apps.get_model("fuel", "FuelType")
    FuelType.objects.filter(is_system=True, user=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("fuel", "0003_alter_fueltype_user"),
    ]

    operations = [
        migrations.RunPython(create_system_fuel_types, reverse_fuel_types),
    ]
