# Generated by Django 5.2.17 on 2026-09-23 02:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora Inicial')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora Final')),
                ('start_odometer', models.PositiveIntegerField(verbose_name='Odômetro Inicial (km)')),
                ('end_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odômetro Final (km)')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Calculada automaticamente ou informada manualmente.', max_digits=10, null=True, verbose_name='Distância (km)')),
                ('origin', models.CharField(max_length=150, verbose_name='Origem')),
                ('destination', models.CharField(max_length=150, verbose_name='Destino')),
                ('purpose', models.CharField(choices=[('personal', 'Pessoal'), ('business', 'Trabalho / Negócios'), ('commute', 'Deslocamento diário'), ('freight', 'Frete / Carga'), ('other', 'Outro')], default='personal', max_length=20, verbose_name='Finalidade')),
                ('rate_per_km', models.DecimalField(blank=True, decimal_places=3, help_text='Taxa para reembolso ou custo unitário.', max_digits=8, null=True, verbose_name='Valor por km (R$/km)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Custo total ou valor reembolsado.', max_digits=10, null=True, verbose_name='Valor Total (R$)')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='Motorista')),
                ('freight_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Frete (R$)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Viagem / Percurso',
                'verbose_name_plural': 'Viagens e Percursos',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['vehicle', 'started_at'], name='trips_trip_vehicle_4c9ded_idx'), models.Index(fields=['vehicle', 'purpose'], name='trips_trip_vehicle_b20aa6_idx')],
            },
        ),
    ]
