[project]
name = "car-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "taboaneiros", email = "taboaneiros@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "black>=26.5.1",
]

[project.scripts]
car-management = "car_management:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
