# Generated by Django 5.2.17 on 2026-09-23 02:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Título da Inspeção')),
                ('odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odômetro (km)')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Inspeção')),
                ('status', models.CharField(choices=[('approved', 'Aprovado'), ('warning', 'Atenção (com ressalvas)'), ('rejected', 'Reprovado (não conforme)')], default='approved', max_length=20, verbose_name='Status Geral')),
                ('notes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='vehicles.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Inspeção / Checklist',
                'verbose_name_plural': 'Inspeções e Checklists',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistInspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='Geral', max_length=50, verbose_name='Categoria')),
                ('title', models.CharField(max_length=150, verbose_name='Item')),
                ('status', models.CharField(choices=[('ok', 'Conforme / OK'), ('attention', 'Atenção / Ressalva'), ('problem', 'Não Conforme / Problema'), ('na', 'Não se aplica')], default='ok', max_length=20, verbose_name='Status')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklistinspection', verbose_name='Inspeção')),
            ],
            options={
                'verbose_name': 'Item de Inspeção',
                'verbose_name_plural': 'Itens de Inspeção',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_system', models.BooleanField(default=False, verbose_name='Modelo Padrão do Sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Modelo de Checklist',
                'verbose_name_plural': 'Modelos de Checklist',
                'ordering': ['-is_system', 'name'],
            },
        ),
        migrations.AddField(
            model_name='checklistinspection',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='checklists.checklisttemplate', verbose_name='Modelo Utilizado'),
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='Geral', max_length=50, verbose_name='Categoria')),
                ('title', models.CharField(max_length=150, verbose_name='Item a Checar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Item de Modelo de Checklist',
                'verbose_name_plural': 'Itens de Modelo de Checklist',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddIndex(
            model_name='checklistinspection',
            index=models.Index(fields=['vehicle', 'checked_at'], name='checklists__vehicle_518610_idx'),
        ),
        migrations.AddIndex(
            model_name='checklistinspection',
            index=models.Index(fields=['vehicle', 'status'], name='checklists__vehicle_425be7_idx'),
        ),
    ]
