# Generated by Django 5.2.17 on 2026-09-23 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('reminder_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('expense', 'Expense / Tax'), ('document', 'Document / License'), ('other', 'Other')], default='maintenance', max_length=20, verbose_name='reminder type')),
                ('due_date', models.DateField(blank=True, help_text='Date when the reminder is due', null=True, verbose_name='due date')),
                ('due_odometer', models.PositiveIntegerField(blank=True, help_text='Odometer reading when the reminder is due', null=True, verbose_name='due odometer (km)')),
                ('alert_days_before', models.PositiveIntegerField(default=15, help_text='Number of days before due date to start alerting', verbose_name='alert days before')),
                ('alert_odometer_before', models.PositiveIntegerField(default=500, help_text='Number of kilometers before due odometer to start alerting', verbose_name='alert km before')),
                ('is_recurring', models.BooleanField(default=False, help_text='Automatically create next reminder when completed?', verbose_name='recurring')),
                ('recurrence_interval_months', models.PositiveIntegerField(blank=True, help_text='Recurrence interval in months', null=True, verbose_name='interval (months)')),
                ('recurrence_interval_km', models.PositiveIntegerField(blank=True, help_text='Recurrence interval in kilometers', null=True, verbose_name='interval (km)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='completed at')),
                ('completed_odometer', models.PositiveIntegerField(blank=True, null=True, verbose_name='completed odometer')),
                ('notify_by_email', models.BooleanField(default=True, help_text='Send email notification when due or overdue', verbose_name='notify by email')),
                ('last_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='last notified at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('service_type', models.ForeignKey(blank=True, help_text='Associated maintenance service type (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='maintenance.servicetype', verbose_name='service type')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
                'db_table': 'reminders_reminder',
                'ordering': ['due_date', 'due_odometer', '-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='reminders_r_vehicle_338cd3_idx'), models.Index(fields=['status', 'due_date'], name='reminders_r_status_82e7f5_idx'), models.Index(fields=['status', 'due_odometer'], name='reminders_r_status_6fbdca_idx')],
            },
        ),
    ]
