# Generated by Django 5.2.16 on 2026-08-01 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('brand', models.CharField(max_length=100, verbose_name='brand')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('version', models.CharField(blank=True, max_length=100, verbose_name='version')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('plate', models.CharField(blank=True, help_text='Vehicle license plate', max_length=20, verbose_name='plate')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('other', 'Other')], default='car', max_length=20, verbose_name='vehicle type')),
                ('fuel_control_type', models.CharField(choices=[('single', 'Single fuel'), ('dual', 'Dual fuel (e.g., gasoline + ethanol)')], default='single', max_length=10, verbose_name='fuel control type')),
                ('initial_odometer', models.PositiveIntegerField(default=0, help_text='Odometer reading when vehicle was added', verbose_name='initial odometer')),
                ('current_odometer_cache', models.PositiveIntegerField(default=0, help_text='Cached current odometer reading (updated on each record)', verbose_name='current odometer')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner_primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='primary owner')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'db_table': 'vehicles_vehicle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='owner', max_length=20, verbose_name='role')),
                ('can_view', models.BooleanField(default=True, verbose_name='can view')),
                ('can_edit', models.BooleanField(default=True, verbose_name='can edit')),
                ('can_transfer', models.BooleanField(default=False, verbose_name='can transfer')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'vehicle ownership',
                'verbose_name_plural': 'vehicle ownerships',
                'db_table': 'vehicles_ownership',
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner_primary', 'is_active'], name='vehicles_ve_owner_p_6cfba5_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner_primary', 'name'], name='vehicles_ve_owner_p_b4f2e9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate'], name='vehicles_ve_plate_f1ecfa_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleownership',
            index=models.Index(fields=['user', 'is_active'], name='vehicles_ow_user_id_41661e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleownership',
            unique_together={('vehicle', 'user')},
        ),
    ]
