# Generated by Django 5.2.17 on 2026-09-23 01:03

import apps.maintenance.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective')], default='preventive', max_length=20, verbose_name='type')),
                ('occurred_at', models.DateField(verbose_name='date')),
                ('odometer', models.PositiveIntegerField(help_text='Vehicle odometer at the time of service', verbose_name='odometer (km)')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total cost of maintenance', max_digits=10, verbose_name='total amount')),
                ('workshop_name', models.CharField(blank=True, help_text='Name of workshop or mechanic', max_length=100, verbose_name='workshop / provider')),
                ('description', models.CharField(blank=True, help_text='Brief description of the service performed', max_length=255, verbose_name='description')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.maintenance.models.maintenance_attachment_upload_path, verbose_name='attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'maintenance',
                'verbose_name_plural': 'maintenances',
                'db_table': 'maintenance_maintenance',
                'ordering': ['-occurred_at', '-odometer'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('default_interval_km', models.PositiveIntegerField(blank=True, help_text='Recommended mileage between services', null=True, verbose_name='default interval (km)')),
                ('default_interval_months', models.PositiveIntegerField(blank=True, help_text='Recommended months between services', null=True, verbose_name='default interval (months)')),
                ('is_system', models.BooleanField(default=False, verbose_name='system')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'service type',
                'verbose_name_plural': 'service types',
                'db_table': 'maintenance_service_type',
                'ordering': ['name'],
            },
        ),
    ]
