# Generated by Django 5.2.17 on 2026-09-23 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        ('reminders', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='reminders.reminder', verbose_name='reminder'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicles.vehicle', verbose_name='vehicle'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='maintenance.servicetype', verbose_name='service type'),
        ),
        migrations.AddIndex(
            model_name='servicetype',
            index=models.Index(fields=['user', 'is_active'], name='maintenance_user_id_50b90c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['vehicle', 'occurred_at'], name='maintenance_vehicle_abd593_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['vehicle', 'maintenance_type'], name='maintenance_vehicle_95673b_idx'),
        ),
    ]
