# Generated by Django 5.2.16 on 2026-08-01 20:38

import apps.expenses.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('kind', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable'), ('other', 'Other')], default='variable', max_length=20, verbose_name='kind')),
                ('is_system', models.BooleanField(default=False, verbose_name='system')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'expense category',
                'verbose_name_plural': 'expense categories',
                'db_table': 'expenses_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateField(verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('odometer', models.PositiveIntegerField(blank=True, help_text='Odometer reading at the time of expense', null=True, verbose_name='odometer (km)')),
                ('vendor_name', models.CharField(blank=True, help_text='Name of the vendor or establishment', max_length=100, verbose_name='vendor')),
                ('is_recurring', models.BooleanField(default=False, help_text='Is this a recurring expense?', verbose_name='recurring')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to=apps.expenses.models.expense_attachment_upload_path, verbose_name='attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='vehicles.vehicle', verbose_name='vehicle')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.expensecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'db_table': 'expenses_expense',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['user', 'is_active'], name='expenses_ca_user_id_1f350e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('user', 'slug')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['vehicle', 'occurred_at'], name='expenses_ex_vehicle_b20cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['vehicle', 'category', 'occurred_at'], name='expenses_ex_vehicle_2873cc_idx'),
        ),
    ]
