# Generated by Django 5.2.17 on 2026-08-17 00:39

import apps.expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.expenses.models.expense_attachment_upload_path,
                verbose_name="attachment",
            ),
        ),
    ]
