# Generated by Django 5.1.7 on 2026-08-17 01:00

from django.db import migrations
from django.utils.text import slugify


def create_system_expense_categories(apps, schema_editor):
    """Create system-wide expense categories."""
    ExpenseCategory = apps.get_model("expenses", "ExpenseCategory")

    categories = [
        "Impostos e taxas",
        "Seguro",
        "Multas",
        "Estacionamento",
        "Pedágio",
        "Lavagem",
        "Conveniência",
        "Financiamento",
        "Outros",
    ]

    for name in categories:
        ExpenseCategory.objects.get_or_create(
            user=None,
            slug=slugify(name),
            defaults={
                "name": name,
                "is_system": True,
                "is_active": True,
            },
        )


def reverse_expense_categories(apps, schema_editor):
    """Remove system-wide expense categories."""
    ExpenseCategory = apps.get_model("expenses", "ExpenseCategory")
    ExpenseCategory.objects.filter(is_system=True, user=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_alter_expensecategory_user"),
    ]

    operations = [
        migrations.RunPython(create_system_expense_categories, reverse_expense_categories),
    ]
