# Generated by Django 5.2.17 on 2026-08-17 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_create_system_expense_categories"),
    ]

    operations = []
