# Generated by Django 5.2.17 on 2026-09-23 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_merge_20260816_2229'),
        ('reminders', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='reminders.reminder', verbose_name='reminder'),
        ),
    ]
